PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX cdao: <http://www.evolutionaryontology.org/cdao/1.0/cdao.owl#>
SELECT DISTINCT ?character ?character_label
FROM <http://kb.phenoscape.org/> 
WHERE 
{ 
?cell cdao:has_State <<%= state %>> .
?cell cdao:belongs_to_Character ?character .
?character rdfs:label ?character_label .
} 
