PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?character ?character_label
FROM <http://kb.phenoscape.org/> 
WHERE 
{ 
?cell obo:CDAO_0000184 <<%= state %>> .
?cell obo:CDAO_0000205 ?character .
?character rdfs:label ?character_label .
} 
