prefix obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX cdao: <http://www.evolutionaryontology.org/cdao/1.0/cdao.owl#>
PREFIX bd: <http://www.bigdata.com/rdf/search#>
SELECT distinct ?state ?state_label
FROM <http://kb.phenoscape.org/>
FROM <http://kb.phenoscape.org/closure>
WHERE 
{ 
?state rdf:type cdao:Standard .
?state rdfs:label ?state_label .
# this query will need to be changed to search for states, using a concatenated character:state label value
# ?state dc:description ?state_desc .
<% if (text) { %>
?state_label bd:search "<%= text %>" .
<% } %>
<% if (entity || quality) { %>
	?state ps:denotes_exemplar ?exemplar .
	?exemplar obo:BFO_0000051 ?part .
	<% if (entity) { %>
	?part rdf:type ?entity . 
	?entity rdfs:subClassOf <<%= sparql_util.partof_iri(entity) %>> .
	<% } %>
	<% if (quality) { %>
	?part obo:BFO_0000053 ?qual .
	?qual rdf:type ?quality .
	?quality rdfs:subClassOf <<%= quality %>> .
	<% } %>
<% } %>
} 

<% if (false && text) { //intentionally disabled %>
ORDER BY desc(?sc)
<% } else { %>
ORDER BY <%= desc ? 'desc(?state_label)' : '?state_label' %>
<% } %>
LIMIT <%= limit %>
OFFSET <%= offset %>