PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX bd: <http://www.bigdata.com/rdf/search#>
SELECT distinct ?state ?state_desc ?rank ?annotation
FROM <http://kb.phenoscape.org/>
FROM <http://kb.phenoscape.org/closure>
WHERE 
{ 
?state rdf:type obo:CDAO_0000045 .
?state dc:description ?state_desc .
<% if (text) { %>
?state_desc bd:search "<%= text %>" .
?state_desc bd:matchAllTerms "true" .
?state_desc bd:rank ?rank .
<% } %>
<% if (entity) { %>
?state rdf:type ?entity . 
?entity rdfs:subClassOf <<%= sparql_util.involves_iri(entity) %>> .
<% } %>
<% if (quality) { %>
?state rdf:type ?quality .
?quality rdfs:subClassOf <<%= sparql_util.involves_iri(quality) %>> .
<% } %>
OPTIONAL
{
?state rdf:type ?annotation .
?annotation rdf:type owl:Restriction .
?annotation owl:onProperty <http://purl.obolibrary.org/obo/IAO_0000219> .
} 
}
<% if (text) { %>
ORDER BY desc(?rank)
<% } else { %>
ORDER BY <%= desc ? 'desc(?state_desc)' : '?state_desc' %>
<% } %>
LIMIT <%= limit %>
OFFSET <%= offset %>

