PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX partof: <http://purl.obolibrary.org/obo/BFO_0000050_some_>
PREFIX ps: <http://vocab.phenoscape.org/>
PREFIX cdao: <http://www.evolutionaryontology.org/cdao/1.0/cdao.owl#>
PREFIX bd: <http://www.bigdata.com/rdf/search#>

SELECT (count(distinct ?state) as ?count)
FROM <http://kb.phenoscape.org/>
FROM <http://kb.phenoscape.org/closure>
WHERE
{
<% if (text) { %>
?state rdfs:label ?state_label .
?state_label bd:search "<%= text %>" .
<% } %>
?state ps:denotes_exemplar ?exemplar .
?exemplar obo:BFO_0000051 ?part .
<% if (entity) { %>
?part rdf:type ?entity . 
?entity rdfs:subClassOf <<%= sparql_util.partof_iri(entity) %>> .
<% } %>
<% if (quality) { %>
?part obo:BFO_0000053 ?qual .
?qual rdf:type ?quality .
?quality rdfs:subClassOf <<%= quality %>> .
<% } %>
}
