PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX partof: <http://purl.obolibrary.org/obo/BFO_0000050_some_http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/>

SELECT (COUNT(DISTINCT ?expression) AS ?count)
FROM <http://kb.phenoscape.org/>
FROM <http://kb.phenoscape.org/closure>
WHERE 
{ 
?annotation rdf:type ps:PhenotypeAnnotation .
?annotation ps:annotated_taxon <<%= taxon %>> .
} 
