PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT (count(*) as ?count)
FROM <http://kb.phenoscape.org/> 
WHERE 
{ 
?character rdf:type obo:CDAO_0000075 . 
} 
