PREFIX ps: <http://vocab.phenoscape.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT (count(distinct ?taxon) as ?count)
FROM <http://kb.phenoscape.org/> 
WHERE 
{ 
?otu rdf:type obo:CDAO_0000138 .
?otu obo:CDAO_0000164 ?taxon .
FILTER EXISTS {?cell obo:CDAO_0000191 ?otu .}
} 
