PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX bd: <http://www.bigdata.com/rdf/search#>

SELECT DISTINCT ?s ?text
FROM <http://kb.phenoscape.org/>
WHERE 
{ 
?s obo:IAO_0000115 ?text . 
} 
BINDINGS ?s { 
<%= _.map(iris, function (item) { return "(<" + item + ">)"; }).join(" ") %>
}