PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/>

SELECT DISTINCT ?s ?label
FROM <http://kb.phenoscape.org/>
WHERE 
{ 
<<%= iri %>> rdfs:subClassOf ?s .
?s rdfs:label ?label .
} 
