DEFINE sql:describe-mode "CBD"
describe ?phenotype ?expression
from <http://kb.phenoscape.org/>
where
{
<<%= character %>> rdf:type ?type .
?type rdf:type owl:Restriction .
?type owl:onProperty <http://purl.obolibrary.org/obo/IAO_0000219> .
?type owl:allValuesFrom ?phenotype .
?phenotype owl:equivalentClass ?expression .
}
