prefix obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://vocab.phenoscape.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
SELECT distinct ?character ?character_label ?state ?state_label
FROM <http://kb.phenoscape.org/>
FROM <http://kb.phenoscape.org/closure>
WHERE 
{ 
# this query will need to be changed to search for states, using a concatenated character:state label value
?character rdfs:label ?character_label .
# ?character dc:description ?character_desc .
<% if (text) { %>
?character_label bif:contains '"<%= text %>"' option(score ?sc).
<% } %>
?state rdfs:label ?state_label .
?cell obo:CDAO_0000184 ?state .
?cell obo:CDAO_0000205 ?character .
<% if (entity || quality) { %>
	?state ps:denotes_exemplar ?exemplar .
	?exemplar obo:BFO_0000051 ?part .
	<% if (entity) { %>
	?part rdf:type ?entity . 
	?entity rdfs:subClassOf <<%= sparql_util.partof_iri(entity) %>> .
	<% } %>
	<% if (quality) { %>
	?part obo:BFO_0000053 ?qual .
	?qual rdf:type ?quality .
	?quality rdfs:subClassOf <<%= quality %>> .
	<% } %>
<% } %>
} 

<% if (text) { %>
ORDER BY desc(?sc)
<% } else { %>
ORDER BY <%= desc ? 'desc(?character_label)' : '?character_label' %>
<% } %>
LIMIT <%= limit %>
OFFSET <%= offset %>